package router

import (
	"io"
	"net/http"

	"github.com/go-chi/chi"
	_ "github.com/myrteametrics/myrtea-ingester-api/v4/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/myrteametrics/myrtea-ingester-api/v4/internals/handlers"
)

// NotImplemented returns a basic message "Not Implemented" when called, and should be use a filler for future handler
func NotImplemented(w http.ResponseWriter, r *http.Request) {
	io.WriteString(w, `{"message":"Not Implemented"}`)
}

func ingesterRouter() http.Handler {
	r := chi.NewRouter()

	ingesterAPI := handlers.NewIngesterHandler()
	r.Post("/data", ingesterAPI.ReceiveData)
	return r
}
