// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: ingester-api.proto

package pb

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BulkIngestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *BulkIngestResponse) Reset() {
	*x = BulkIngestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingester_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkIngestResponse) ProtoMessage() {}

func (x *BulkIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingester_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkIngestResponse.ProtoReflect.Descriptor instead.
func (*BulkIngestResponse) Descriptor() ([]byte, []int) {
	return file_ingester_api_proto_rawDescGZIP(), []int{0}
}

func (x *BulkIngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BulkIngestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID         string         `protobuf:"bytes,1,opt,name=UUID,json=uuid,proto3" json:"UUID,omitempty"`
	DocumentType string         `protobuf:"bytes,2,opt,name=DocumentType,json=documentType,proto3" json:"DocumentType,omitempty"`
	MergeConfigs []*MergeConfig `protobuf:"bytes,3,rep,name=MergeConfigs,json=merge,proto3" json:"MergeConfigs,omitempty"`
	Documents    []*Document    `protobuf:"bytes,4,rep,name=Documents,json=docs,proto3" json:"Documents,omitempty"`
}

func (x *BulkIngestRequest) Reset() {
	*x = BulkIngestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingester_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkIngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkIngestRequest) ProtoMessage() {}

func (x *BulkIngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingester_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkIngestRequest.ProtoReflect.Descriptor instead.
func (*BulkIngestRequest) Descriptor() ([]byte, []int) {
	return file_ingester_api_proto_rawDescGZIP(), []int{1}
}

func (x *BulkIngestRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *BulkIngestRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *BulkIngestRequest) GetMergeConfigs() []*MergeConfig {
	if x != nil {
		return x.MergeConfigs
	}
	return nil
}

func (x *BulkIngestRequest) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type MergeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExistingAsMaster bool     `protobuf:"varint,1,opt,name=ExistingAsMaster,json=mode,proto3" json:"ExistingAsMaster,omitempty"`
	Mode             string   `protobuf:"bytes,2,opt,name=Mode,json=existingAsMaster,proto3" json:"Mode,omitempty"`
	Type             string   `protobuf:"bytes,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	LinkKey          string   `protobuf:"bytes,4,opt,name=LinkKey,json=linkKey,proto3" json:"LinkKey,omitempty"`
	Groups           []*Group `protobuf:"bytes,5,rep,name=Groups,json=groups,proto3" json:"Groups,omitempty"`
}

func (x *MergeConfig) Reset() {
	*x = MergeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingester_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeConfig) ProtoMessage() {}

func (x *MergeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ingester_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeConfig.ProtoReflect.Descriptor instead.
func (*MergeConfig) Descriptor() ([]byte, []int) {
	return file_ingester_api_proto_rawDescGZIP(), []int{2}
}

func (x *MergeConfig) GetExistingAsMaster() bool {
	if x != nil {
		return x.ExistingAsMaster
	}
	return false
}

func (x *MergeConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *MergeConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MergeConfig) GetLinkKey() string {
	if x != nil {
		return x.LinkKey
	}
	return ""
}

func (x *MergeConfig) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Condition             string       `protobuf:"bytes,1,opt,name=Condition,json=condition,proto3" json:"Condition,omitempty"`
	FieldReplace          []string     `protobuf:"bytes,2,rep,name=FieldReplace,json=fieldReplace,proto3" json:"FieldReplace,omitempty"`
	FieldReplaceIfMissing []string     `protobuf:"bytes,3,rep,name=FieldReplaceIfMissing,json=fieldReplaceIfMissing,proto3" json:"FieldReplaceIfMissing,omitempty"`
	FieldMerge            []string     `protobuf:"bytes,4,rep,name=FieldMerge,json=fieldMerge,proto3" json:"FieldMerge,omitempty"`
	FieldKeepLatest       []string     `protobuf:"bytes,6,rep,name=FieldKeepLatest,json=fieldMath,proto3" json:"FieldKeepLatest,omitempty"`
	FieldKeepEarliest     []string     `protobuf:"bytes,7,rep,name=FieldKeepEarliest,json=fieldKeepLatest,proto3" json:"FieldKeepEarliest,omitempty"`
	FieldForceUpdate      []string     `protobuf:"bytes,8,rep,name=FieldForceUpdate,json=fieldKeepEarliest,proto3" json:"FieldForceUpdate,omitempty"`
	FieldMath             []*FieldMath `protobuf:"bytes,5,rep,name=FieldMath,json=fieldForceUpdate,proto3" json:"FieldMath,omitempty"`
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingester_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_ingester_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_ingester_api_proto_rawDescGZIP(), []int{3}
}

func (x *Group) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Group) GetFieldReplace() []string {
	if x != nil {
		return x.FieldReplace
	}
	return nil
}

func (x *Group) GetFieldReplaceIfMissing() []string {
	if x != nil {
		return x.FieldReplaceIfMissing
	}
	return nil
}

func (x *Group) GetFieldMerge() []string {
	if x != nil {
		return x.FieldMerge
	}
	return nil
}

func (x *Group) GetFieldKeepLatest() []string {
	if x != nil {
		return x.FieldKeepLatest
	}
	return nil
}

func (x *Group) GetFieldKeepEarliest() []string {
	if x != nil {
		return x.FieldKeepEarliest
	}
	return nil
}

func (x *Group) GetFieldForceUpdate() []string {
	if x != nil {
		return x.FieldForceUpdate
	}
	return nil
}

func (x *Group) GetFieldMath() []*FieldMath {
	if x != nil {
		return x.FieldMath
	}
	return nil
}

type FieldMath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expression  string `protobuf:"bytes,1,opt,name=Expression,json=expression,proto3" json:"Expression,omitempty"`
	OutputField string `protobuf:"bytes,2,opt,name=OutputField,json=outputField,proto3" json:"OutputField,omitempty"`
}

func (x *FieldMath) Reset() {
	*x = FieldMath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingester_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldMath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMath) ProtoMessage() {}

func (x *FieldMath) ProtoReflect() protoreflect.Message {
	mi := &file_ingester_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMath.ProtoReflect.Descriptor instead.
func (*FieldMath) Descriptor() ([]byte, []int) {
	return file_ingester_api_proto_rawDescGZIP(), []int{4}
}

func (x *FieldMath) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *FieldMath) GetOutputField() string {
	if x != nil {
		return x.OutputField
	}
	return ""
}

type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string          `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Index     string          `protobuf:"bytes,2,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	IndexType string          `protobuf:"bytes,3,opt,name=IndexType,json=type,proto3" json:"IndexType,omitempty"`
	Source    *_struct.Struct `protobuf:"bytes,4,opt,name=Source,json=source,proto3" json:"Source,omitempty"`
}

func (x *Document) Reset() {
	*x = Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ingester_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_ingester_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_ingester_api_proto_rawDescGZIP(), []int{5}
}

func (x *Document) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Document) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Document) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

func (x *Document) GetSource() *_struct.Struct {
	if x != nil {
		return x.Source
	}
	return nil
}

var File_ingester_api_proto protoreflect.FileDescriptor

var file_ingester_api_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x12, 0x42, 0x75, 0x6c, 0x6b, 0x49, 0x6e,
	0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x11, 0x42, 0x75, 0x6c, 0x6b, 0x49, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x2c, 0x0a, 0x0c, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65,
	0x72, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x05, 0x6d, 0x65, 0x72, 0x67, 0x65,
	0x12, 0x25, 0x0a, 0x09, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x72, 0x67,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1e, 0x0a, 0x10, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x41, 0x73, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x41,
	0x73, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4c,
	0x69, 0x6e, 0x6b, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69,
	0x6e, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x06, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0xd0, 0x02, 0x0a, 0x05, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x15, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x49, 0x66, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x15, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x49, 0x66, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0f, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4b, 0x65, 0x65, 0x70, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x74, 0x68, 0x12, 0x2a,
	0x0a, 0x11, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4b, 0x65, 0x65, 0x70, 0x45, 0x61, 0x72, 0x6c, 0x69,
	0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x4b, 0x65, 0x65, 0x70, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x10, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4b, 0x65, 0x65, 0x70, 0x45,
	0x61, 0x72, 0x6c, 0x69, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4d, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x74, 0x68, 0x52, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x46, 0x6f, 0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x4d, 0x0a, 0x09, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x7a, 0x0a, 0x08, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x17, 0x0a, 0x09,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x32, 0x45, 0x0a, 0x08, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x39, 0x0a, 0x06, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x49, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x19, 0x48,
	0x01, 0x5a, 0x15, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ingester_api_proto_rawDescOnce sync.Once
	file_ingester_api_proto_rawDescData = file_ingester_api_proto_rawDesc
)

func file_ingester_api_proto_rawDescGZIP() []byte {
	file_ingester_api_proto_rawDescOnce.Do(func() {
		file_ingester_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_ingester_api_proto_rawDescData)
	})
	return file_ingester_api_proto_rawDescData
}

var file_ingester_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ingester_api_proto_goTypes = []interface{}{
	(*BulkIngestResponse)(nil), // 0: pb.BulkIngestResponse
	(*BulkIngestRequest)(nil),  // 1: pb.BulkIngestRequest
	(*MergeConfig)(nil),        // 2: pb.MergeConfig
	(*Group)(nil),              // 3: pb.Group
	(*FieldMath)(nil),          // 4: pb.FieldMath
	(*Document)(nil),           // 5: pb.Document
	(*_struct.Struct)(nil),     // 6: google.protobuf.Struct
}
var file_ingester_api_proto_depIdxs = []int32{
	2, // 0: pb.BulkIngestRequest.MergeConfigs:type_name -> pb.MergeConfig
	5, // 1: pb.BulkIngestRequest.Documents:type_name -> pb.Document
	3, // 2: pb.MergeConfig.Groups:type_name -> pb.Group
	4, // 3: pb.Group.FieldMath:type_name -> pb.FieldMath
	6, // 4: pb.Document.Source:type_name -> google.protobuf.Struct
	1, // 5: pb.Ingester.Ingest:input_type -> pb.BulkIngestRequest
	0, // 6: pb.Ingester.Ingest:output_type -> pb.BulkIngestResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ingester_api_proto_init() }
func file_ingester_api_proto_init() {
	if File_ingester_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ingester_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkIngestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingester_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkIngestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingester_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingester_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingester_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldMath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ingester_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ingester_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingester_api_proto_goTypes,
		DependencyIndexes: file_ingester_api_proto_depIdxs,
		MessageInfos:      file_ingester_api_proto_msgTypes,
	}.Build()
	File_ingester_api_proto = out.File
	file_ingester_api_proto_rawDesc = nil
	file_ingester_api_proto_goTypes = nil
	file_ingester_api_proto_depIdxs = nil
}
