### DO NOT COMMIT ANY ENVIRONMENT CHANGE ON THIS FILE
### If you need to use another environment, edit this file localy, and do not propagate the changes.

# Enable or disable debug mode
# Debug mode print all configuration variables when the binary start
# WARNING: every single variable will be printed, including password or sensitive data
# Default value: "false"
DEBUG_MODE = "false"

# Enable or disable production log
# Default value: true
LOGGER_PRODUCTION = "true"

# Specify the server running port. API (including swagger) will be reachable through this port
# Default value: "9001"
HTTP_SERVER_PORT = "9001"

# Enable or disable TLS and HTTPS server security (false = HTTPS / true = HTTP)
# If HTTP_SERVER_ENABLE_TLS = true, HTTP_SERVER_SSL_FILE_CRT and HTTP_SERVER_SSL_FILE_KEY must be specified
# Default value: "false"
HTTP_SERVER_ENABLE_TLS = "false"

# TLS certificate file path
# Default value: "certs/server.rsa.crt"
HTTP_SERVER_TLS_FILE_CRT = "certs/server.rsa.crt"

# TLS private key file path
# Default value: "certs/server.rsa.key"
HTTP_SERVER_TLS_FILE_KEY = "certs/server.rsa.key"

# Enable or disable CORS policy on the API
# See https://enable-cors.org/
# Default value: "false"
HTTP_SERVER_API_ENABLE_CORS = "true"

# Enable or disable API security
# If unsecured = false, a valid JWT (JSON Web Token) is required to access the API
# This JWT is delivered using the /login endpoint (which required a login and a password)
# If HTTP_SERVER_API_ENABLE_SECURITY = false, no JWT is required and all endpoints can be called freely
# Default value: "true"
HTTP_SERVER_API_ENABLE_SECURITY = "false"

# Enable or disable API Gateway mode
# If HTTP_SERVER_API_ENABLE_GATEWAY_MODE = true, the API will still required a JWT but no validation will be done on this JWT
# Be aware that in gateway mode, every JWT MUST have been validated by another layer of security (in this case, an API Gateway using the auth-api)
# The auth-api will be responsible to deliver the tokens (/login) and to validate the tokens (/validate)
# Default value: "false"
HTTP_SERVER_API_ENABLE_GATEWAY_MODE = "false"

# Enable or disable verbose API error
# If enabled, in case of error, the API will returns additional information to help debugging
# Do not enable in production
# Default value: "false
HTTP_SERVER_API_ENABLE_VERBOSE_ERROR = "false"

# Specify the instance name
# The instance name must be the same in every components in the stack to ensure proper working conditions
# Default value: "myrtea"
INSTANCE_NAME = "myrtea"

# Specify the hostname used to access the swagger UI
# If not set (or incorrect), the swagger UI will be available but will not be usable (using execute on endpoints)
# Default value: "localhost:9001"
SWAGGER_HOST = "localhost:9001"

# Specify the basepath used to access the swagger UI
# If not set (or incorrect), the swagger UI will be available but will not be usable (using execute on endpoints)
# Default value: "/api/v5"
SWAGGER_BASEPATH = "/api/v5"

# Specify the elasticsearch URLS
# Array of URLS might not work using environment variable (should be fixed soon)
# Default value: 7
ELASTICSEARCH_VERSION = 6

# Specify the elasticsearch URLS
# Array of URLS might not work using environment variable (should be fixed soon)
# Default value: "http://localhost:9200"
ELASTICSEARCH_URLS = ["http://localhost:9200"]

ELASTICSEARCH_HTTP_TIMEOUT = "1m"

# Specify if pre-update multi-get should be done directly to a specific index
# Default value: false
ELASTICSEARCH_DIRECT_MULTI_GET_MODE = "false"

# Specify the maximum number of concurrent worker by type of ingested document (1 type of document = n workers)
# Default value: 2
INGESTER_MAXIMUM_WORKERS = "2"

# Specify the typed-ingesters maximum queue size
# Default value: "5000"
TYPEDINGESTER_QUEUE_BUFFER_SIZE = "500"

# Specify the workers maximum queue size
# Default value: "5000"
WORKER_QUEUE_BUFFER_SIZE = "500"

# Specify the workers maximum buffer size before document flushing to elasticsearch
# Default value: 2000
WORKER_MAXIMUM_BUFFER_SIZE = "2000"

# Specify the timeout before document flushing to elasticsearch (in seconds)
# Default value: 10
WORKER_FORCE_FLUSH_TIMEOUT_SEC = "10"

# Enable dry run mode for elasticsearch 
# If DEBUG_DRY_RUN_ELASTICSEARCH = true, no interaction will be done with elasticsearch (no enrichment and no document post)
# Default value: false
DEBUG_DRY_RUN_ELASTICSEARCH = "false"